PAN = "PAN"
TILT = "TILT"
PAN_FINE = "PAN_FINE"
TILT_FINE = "TILT_FINE"
DIMMER = "DIMMER"
SHUTTER = "SHUTTER"
SPEED = "SPEED"

COLOUR_WHEEL = "COLOUR_WHEEL"
GOBO_WHEEL = "GOBO_WHEEL"

PRISM = "PRISM"
FOCUS = "FOCUS"
ZOOM = "ZOOM"

RESET = "RESET"

UNKNOWN = "UNKNOWN"